"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

ben = range(1,1000)
l = len(ben[:3])
new = []
n = 0
b = 0
c = 1

for i in ben:
    if i < l:
        new.append(i)
    else:
        n = new[b] + new[c]
        new.append(n)
        c += 1
        b += 1

# print(new)
total = 0
for even in new:
    if even % 2 == 0 and even < 4000000:
        total += even

print(total)
